apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: wordpress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-mysql-storage
  hostPath:
    path: /data
    type: DirectoryOrCreate