apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  Namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    storageClassName: pv-mysql-storage