apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsUser: 33   # UID de www-data
        fsGroup: 33     # GID de www-data, applique les permissions sur tous les volumes
      containers:
      - name: wordpress-container
        image: wordpress:latest
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-cluster-ip  # Correspond au nom du service MYSQL
          - name: WORDPRESS_DB_USER
            value: loic
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_password
#        volumeMounts:
#          - name: wordpress-volume
#            mountPath: /var/www/html
#      volumes:
#        - name: wordpress-volume
#          hostPath:
#            path: /data-wordpress
#            type: DirectoryOrCreate
