apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodeport: 30080
  type: NodePort